manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
<<<<<<< HEAD
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main
=======
>>>>>>> 426a094dcd313c38cad0df8e9db7d46610b29876
  self:
    path: config